version: '2.0'
services:
    nginx:
        image: nginx:stable-alpine
        restart: always
        volumes:
            - './apps/php-test/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
          - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
          - './apps/:/usr/src/apps'
        restart: always
        env_file:
            - .env
        user: ${LOCAL_USER}